"""add care recipients and user profile fields

Revision ID: be52a55336ad
Revises: e81a46188aec
Create Date: 2026-09-04 13:59:05.586848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be52a55336ad'
down_revision = 'e81a46188aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('care_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_recipients_nurse_id'), ['nurse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_care_recipients_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='nurse', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_line_user_id'))
        batch_op.alter_column(
            'line_user_id',
            new_column_name='line_id',
            existing_type=mysql.VARCHAR(length=64),
            type_=sa.String(length=128),
            existing_nullable=False,
        )
        batch_op.create_index(batch_op.f('ix_users_line_id'), ['line_id'], unique=True)
        batch_op.create_check_constraint('ck_users_role', "role IN ('owner', 'nurse')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('ck_users_role', type_='check')
        batch_op.drop_index(batch_op.f('ix_users_line_id'))
        batch_op.alter_column(
            'line_id',
            new_column_name='line_user_id',
            existing_type=mysql.VARCHAR(length=128),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.create_index(batch_op.f('ix_users_line_user_id'), ['line_user_id'], unique=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')
        batch_op.drop_column('language')

    with op.batch_alter_table('care_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_recipients_owner_id'))
        batch_op.drop_index(batch_op.f('ix_care_recipients_nurse_id'))

    op.drop_table('care_recipients')
    # ### end Alembic commands ###
