"""diary add ai analysis

Revision ID: 446371083802
Revises: c3d4e5f6a7b8
Create Date: 2026-09-05 15:50:11.664443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446371083802'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_analysis', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.drop_column('ai_analysis')

    # ### end Alembic commands ###
