"""add chat and stress tables

Revision ID: e46351fe0391
Revises: 2c3d4e5f6a7b
Create Date: 2026-09-05 21:45:46.541045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46351fe0391'
down_revision = '2c3d4e5f6a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stress_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("source IN ('chat', 'diary')", name='ck_stress_events_source'),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stress_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stress_events_nurse_id'), ['nurse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stress_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('care_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('care_recipient_id', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), server_default='0.7', nullable=False),
    sa.Column('guardrail', sa.Text(), nullable=True),
    sa.Column('generated_profile', sa.JSON(), nullable=True),
    sa.Column('baseline_answers', sa.JSON(), nullable=True),
    sa.Column('baseline_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('temperature >= 0 AND temperature <= 2', name='ck_care_agents_temperature'),
    sa.ForeignKeyConstraint(['care_recipient_id'], ['care_recipients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('care_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_agents_care_recipient_id'), ['care_recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_care_agents_user_id'), ['user_id'], unique=False)

    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('care_agent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('mood_weather', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("mood_weather IS NULL OR mood_weather IN ('sunny', 'cloudy', 'rainy', 'storm')", name='ck_chat_rooms_mood_weather'),
    sa.ForeignKeyConstraint(['care_agent_id'], ['care_agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_rooms_care_agent_id'), ['care_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_rooms_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_rooms_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("sender IN ('user', 'ai')", name='ck_chat_messages_sender'),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_room_id'), ['room_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_room_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_rooms_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_rooms_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_rooms_care_agent_id'))

    op.drop_table('chat_rooms')
    with op.batch_alter_table('care_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_agents_user_id'))
        batch_op.drop_index(batch_op.f('ix_care_agents_care_recipient_id'))

    op.drop_table('care_agents')
    with op.batch_alter_table('stress_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stress_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_stress_events_nurse_id'))

    op.drop_table('stress_events')
    # ### end Alembic commands ###
